[STACKED] feat(rule): :sparkles: create the geolocation-precision-processor [CARROT-790]
carrot-foundation/audit-rules pull request #238
Opened 2024-04-26 21:01 UTC by AMarcosCastelo

### Summary

This is the processor that will apply the new rule to the `geolocation-precision` rules.

### Related links

https://app.clickup.com/t/3005225/CARROT-794

---

- [x] **I, the PR author, declare that this PR works as expected and does not break any service. I also declare that I gave my best to apply all of the best practices and that I'm leaving the code better than I found it.**

2024-04-26 21:04 UTC, gabrielsl96 submitted a review, later dismissed

2024-04-29 10:59 UTC, cris-santos approved these changes

2024-04-29 10:59 UTC, cris-santos commented on libs/methodologies/bold/matchers/src/document.matchers.ts
> +export const participantHomologationCriteria = (subtype: DocumentSubtype) => ({
será que não valeria a pena declarar o type de retorno da função? que aí fica claro o que ela espera retornar e evita possíveis inconsitências

2024-04-29 10:59 UTC, cris-santos commented on libs/methodologies/bold/testing/src/stubs/document.stubs.ts
> +  partialParticipantHomologationsDocument?: PartialDeep<Document>,
uma alternativa seria chamar de `participantHomologationGroup` ao invés de `participantHomologations` (que eu tbm não vejo problema de manter dessa forma)

2024-04-29 10:59 UTC, cris-santos commented on libs/methodologies/bold/testing/src/stubs/document.stubs.ts
> +  partialMethodologyDefinitionDocument?: PartialDeep<Document>,
pra simplificar a leitura e facilitar possíveis alterações no nome dos métodos, uma opção seria omitir o nome da função do nome do argumento. Que aí se a função for renomeada, por exemplo, não precisaria renomear o arg tbm (mesma sugestão para as funções seguintes)
```suggestion
  partialDocument?: PartialDeep<Document>,
```

2024-04-29 12:47 UTC, sangalli commented on libs/methodologies/bold/types/src/enum.types.ts
> +  RECYCLER = 'Recycler',
Não sei qual é o certo, mas no documento de exemplo do @gabrielsl96 vi que ele usou tudo em letras maiúsculas
https://carrot-public-search-5e49oyqwv-solidos.vercel.app/document/b1c9be16-8471-45ea-90b3-09124fbcccb9

2024-04-29 12:53 UTC, sangalli commented on libs/methodologies/bold/processors/src/geolocation-precision-processor.ts
> +export abstract class GeolocationPrecisionRuleProcessor extends RuleDataProcessor {
1. Olhando pelo nome do arquivo `geolocation-precision-procesor`, ele não é específico nem para pick-up nem para drop-off, correto? A ideia de um processor é que ele já tenha uma relação direta como uma regra. Para esse caso, como exatamente você está planejando?
2. A regra de fato vai ser aplicada tanto para SOURCE como para RECYCLER?

2024-04-29 13:04 UTC, sangalli requested changes

2024-04-29 13:04 UTC, sangalli commented on libs/methodologies/bold/processors/src/geolocation-precision-processor.ts
> +  override async process(ruleInput: RuleInput): Promise<RuleOutput> {
Por que precisou fazer esse override?

2024-04-29 13:04 UTC, sangalli commented on libs/methodologies/bold/processors/src/geolocation-precision-processor.ts
> +            metadataAttributeValueIsAnyOf(MOVE_TYPE, [DROP_OFF]),
Esse DROP_OFF que está aqui deveria vir da implementação concreta, correot?

2024-04-29 13:04 UTC, sangalli commented on libs/methodologies/bold/processors/src/geolocation-precision-processor.ts
> +export abstract class GeolocationPrecisionRuleProcessor extends RuleDataProcessor {
Depois da nossa conversa com slack, entendi que aqui é abstrato.
Mas fiquei com uma outra dúvida, todos os participantes do tipo `SOURCE` serão homologado ou a plataforma vai trabalhar com participantes não homologados também?
A pergunta é pra entender se poderemos descartar completamente a verificação de endereço via Google Maps API ou se existe algum caso em que ainda deveríamos usá-la.

2024-04-29 13:04 UTC, AMarcosCastelo commented on libs/methodologies/bold/types/src/enum.types.ts
> +  RECYCLER = 'Recycler',
Acho que utilizar tudo com letras maiúsculas iria tirar do padrão o `DocumentSubtype` do que é hoje. Acho que valeríamos seguir com capitalize e alterar os documentos de `DEV`.

2024-04-29 13:09 UTC, sangalli commented on libs/methodologies/bold/matchers/src/document.matchers.ts
> +});
Só alertando de um problema que tivemos em outro caso: atualmente nossos matchers fazer buscas parciais. Ou seja, se passar somente `category` e `type`, ele vai retornar todos os documentos com essa `category` e `type` e QUALQUER valor de `subtype`. Acho que aqui não vai dar problema, mas é algo para ficarmos atentos. Algumas alternativas que fiquei pensando agora:
1. O matcher `PARTICIPANT_HOMOLOGATION` poderia chamar ``PARTICIPANT_HOMOLOGATION_PARTIAL_MATCH` para ficar mais evidente
2. Poderíamos mudar a lógica do matcher para só fazer buscas exatas
3. Poderíamos adicionar um parâmetro na função de buscar documentos para escolher se quer fazer busca exata ou não

2024-04-29 13:14 UTC, sangalli commented on libs/methodologies/bold/processors/src/geolocation-precision-processor.spec.ts
> +  };
Vou dar uma ideia, mas não trabalhe nisso agora porque iria levar bastante tempo pra implementar. Se achar a ideia interessante, fica a vontade para criar uma task de melhoria. Poderíamos ter um método para fazer um stub da estrutura de documentos, algo como `stubDocumentsByQueryCriteria(participantHomologationCriteria)`, talvez permitindo passar atributos adicionar para alguns documentos de alguma forma. Já vi vários lugares fazendo stubs de criteria, e acho que isso poderia simplificar a criação de testes.

2024-04-29 17:56 UTC, AMarcosCastelo commented on libs/methodologies/bold/processors/src/geolocation-precision-processor.ts
> +export abstract class GeolocationPrecisionRuleProcessor extends RuleDataProcessor {
Conversei com o Bertolli, e convenci ele a remover a necessidade do Google API.

2024-04-29 18:01 UTC, AMarcosCastelo commented on libs/methodologies/bold/processors/src/geolocation-precision-processor.spec.ts
> +  };
Poderia ser um stub ou um builder que prepara todos os documentos, que era a minha ideia para as regras de Offer. Mas acho a ideia interessante e acho que estamos alinhado. Podemos trabalhar nisso nos débitos técnicos.

2024-04-29 18:24 UTC, cris-santos approved these changes

2024-04-29 18:27 UTC, merged