feat: config assume role smaug [CARROT-808]
carrot-foundation/audit-rules pull request #242
Opened 2024-05-03 21:31 UTC by gabrielsl96

### Summary

Config assume role smaug

### Details

* [feat: config assume role smaug [CARROT-808]](https://github.com/carrot-foundation/audit-rules/commit/36413f63097323f4880c09dbd2f95c56a018d7ad)

### Related links

Task: https://app.clickup.com/t/3005225/CARROT-808

---

- [x] **I, the PR author, declare that this PR works as expected and does not break any service. I also declare that I gave my best to apply all of the best practices and that I'm leaving the code better than I found it.**

2024-05-03 21:31 UTC, cris-santos commented
Task linked: [CARROT-808 Configurar IAM assumeRole para o Elrond se conectar ao Smaug](https://app.clickup.com/t/3005225/CARROT-808)

2024-05-06 10:20 UTC, cris-santos requested changes

2024-05-06 10:20 UTC, cris-santos commented on libs/shared/rule/result/src/rule-result.helpers.ts
> +export const assignRequest = async ({
fiquei um pouco confuso com o nome, não seria `signRequest`?

2024-05-06 10:20 UTC, cris-santos commented on libs/shared/rule/result/src/rule-result.helpers.ts
> +    protocol: 'https',
só pra confirmar, precisamos passar os campos `hostname` e `path` vazios? já não é o valor padrão?

2024-05-06 10:20 UTC, cris-santos commented on libs/shared/rule/result/src/rule-result.helpers.ts
> +}) => {
pra garantir, acho que valeria a pena incluir a tipagem de retorno

2024-05-06 13:25 UTC, gabrielsl96 commented on libs/shared/rule/result/src/rule-result.helpers.ts
> +    protocol: 'https',
Pois é, são campos obrigatórios.

Poderia fazer um split na url para tratar esses campos, mas seria só um trabalho desnecessário

2024-05-06 16:47 UTC, cris-santos approved these changes

2024-05-06 16:48 UTC, merged