feat: add lambda to commit rules metadata [CARROT-518]
carrot-foundation/audit-rules pull request #246
Opened 2024-05-08 18:49 UTC by GLGuilherme

### Summary

_Create lambda to commit rules metadata._

### Details

_Create lambda to commit rules metadata using octokit._

### Related links
https://app.clickup.com/t/3005225/CARROT-518

---

- [X] **I, the PR author, declare that this PR works as expected and does not break any service. I also declare that I gave my best to apply all of the best practices and that I'm leaving the code better than I found it.**

2024-05-08 18:49 UTC, cris-santos commented
Task linked: [CARROT-518 [Deploy] Criar lambda ativado pelo S3 para atualizar arquivos de referência de regras e fazer commit](https://app.clickup.com/t/3005225/CARROT-518)

2024-05-09 03:48 UTC, RafaPalau approved these changes

2024-05-09 16:59 UTC, cris-santos requested changes

2024-05-09 16:59 UTC, cris-santos commented on apps/rules/infra/aws-lambda/src/metadata-commit.tf
> +resource "aws_iam_policy" "rule_metadata_commit_lambda_dlq_policy" {
como o namespace já é específico pra cada recurso, acho que não precisaria incluir o sufixo de cada recurso. Nesse caso daria pra remover o `_policy`, em outros daria pra remover o `_iam_role`, `_policy_attachment`, etc. Pra diminuir mais ainda o nome, não veria problema em remover o prefixo `rule_` tbm

2024-05-09 16:59 UTC, cris-santos commented on apps/rules/infra/aws-lambda/src/metadata-commit.tf
> +resource "aws_iam_policy" "rule_metadata_commit_lambda_s3_policy" {
só pra confirmar, esse lambda precisa dessa permissão pra acessar o S3? ela não é pro bucket de regras?

2024-05-09 16:59 UTC, cris-santos commented on apps/rules/infra/aws-lambda/src/metadata-commit.tf
> +  role       = "rule-metadata-commit-role"
fico pensando se não valeria a pena adicionar o contexto no nome do role, todos acabaram ficando com o mesmo nome. Não sei se vai dar conflito tbm na hora de criar, acho que não poderia ter vários roles com o mesmo nome

2024-05-10 09:18 UTC, cris-santos requested changes

2024-05-10 09:18 UTC, cris-santos commented on apps/rules/metadata-commit/src/lambda.ts
> +  `apps/rules/infra/aws-lambda/src/rules/${process.env['NODE_ENV']}.json`;
o environment na verdade é diferente do `NODE_ENV`. Ambos são com `NODE_ENV === 'production'`. Aqui a gente precisaria usar uma variável ambiente chamada `ENVIRONMENT` ou algo do tipo

2024-05-10 09:18 UTC, cris-santos commented on apps/rules/metadata-commit/src/lambda.ts
> +  });
uma alternativa seria usar o `assertClone` do `typia`

2024-05-10 09:18 UTC, cris-santos commented on apps/rules/metadata-commit/src/lambda.ts
> +  const cloneData = assert<Rules>({
pra ficar mais claro do que se trata, acho que valeria a pena renomear para `clonedRules` ou `rulesClone`,ou algo do tipo. `cloneData` não fica claro de qual data se trata

2024-05-10 09:18 UTC, cris-santos commented on apps/rules/metadata-commit/src/lambda.ts
> +    ...JSON.parse(data.toLocaleString()),
uma alternativa seria usar o `assertParse` do `typia`

2024-05-10 09:18 UTC, cris-santos commented on apps/rules/metadata-commit/src/lambda.ts
> +}): Promise<string> => {
acho que o nome desse método não ficou muito claro, o nome dele é `createTree` e ele retorna um `sha`. Não ficou claro de qual árvore se trata e nem qual `sha` está sendo retornado. Pelo que eu entendi ele retorna o git SHA do último commit, seria isso? Se for, uma alternativa seria chamar de `getLastGitCommitSha`

2024-05-10 09:18 UTC, cris-santos commented on apps/rules/metadata-commit/src/lambda.ts
pra separar melhor o código e diminuir o tamanho do arquivo, acho que valeria a pena criar um arquivo de helpers e separar os helpers do lambda

2024-05-10 09:18 UTC, cris-santos commented on apps/rules/metadata-commit/src/lambda.ts
> +    ref: `heads/${process.env['REFERENCE_BRANCH']}`,
nesse arquivo tem várias variáveis ambiente que estão sendo usadas mas nenhuma está sendo validada que de fato existe. Pra garantir, acho que seria importante validar que elas estão preenchidas de acordo com o esperado. Uma forma seria criar um type e validar com o typia, tipo:
```typescript
interface EnvironmentVariables {
  REFERENCE_BRANCH: NonEmptyString;
  ...outrasVariáveis
}

const environmentVariables = assertPrune<EnvironmentVariables>(process.env);
```

2024-05-10 12:13 UTC, GLGuilherme commented on apps/rules/infra/aws-lambda/src/metadata-commit.tf
> +resource "aws_iam_policy" "rule_metadata_commit_lambda_s3_policy" {
É necessário porque no Lambda ele chama o SDK para pegar informações do objeto do S3

2024-05-10 13:34 UTC, GLGuilherme commented on apps/rules/infra/aws-lambda/src/metadata-commit.tf
> +resource "aws_iam_policy" "rule_metadata_commit_lambda_dlq_policy" {
Feito

2024-05-10 13:34 UTC, GLGuilherme commented on apps/rules/infra/aws-lambda/src/metadata-commit.tf
> +  role       = "rule-metadata-commit-role"
Feito

2024-05-10 13:34 UTC, GLGuilherme commented on apps/rules/metadata-commit/src/lambda.ts
> +  `apps/rules/infra/aws-lambda/src/rules/${process.env['NODE_ENV']}.json`;
Feito

2024-05-10 13:34 UTC, GLGuilherme commented on apps/rules/metadata-commit/src/lambda.ts
> +  });
Feito

2024-05-10 13:34 UTC, GLGuilherme commented on apps/rules/metadata-commit/src/lambda.ts
> +  const cloneData = assert<Rules>({
Feito

2024-05-10 13:34 UTC, GLGuilherme commented on apps/rules/metadata-commit/src/lambda.ts
> +    ...JSON.parse(data.toLocaleString()),
Feito

2024-05-10 13:34 UTC, GLGuilherme commented on apps/rules/metadata-commit/src/lambda.ts
> +}): Promise<string> => {
Feito

2024-05-10 13:34 UTC, GLGuilherme commented on apps/rules/metadata-commit/src/lambda.ts
> +    ref: `heads/${process.env['REFERENCE_BRANCH']}`,
Feito

2024-05-10 13:37 UTC, GLGuilherme commented on apps/rules/metadata-commit/src/lambda.ts
> +    ...JSON.parse(data.toLocaleString()),
Feito

2024-05-10 13:59 UTC, cris-santos submitted a review, later dismissed

2024-05-10 13:59 UTC, cris-santos commented on apps/rules/metadata-commit/src/lambda.types.ts
> +export type Rules = { rules: Record<string, Record<string, string>> };
como só tem uma propriedade, será que não valeria a pena passar ela pra raíz?
```suggestion
export type Rules = Record<string, Record<string, string>>;
```

2024-05-10 16:40 UTC, cris-santos approved these changes

2024-05-10 16:40 UTC, andtankian approved these changes

2024-05-10 16:41 UTC, merged